### ISSUE TITLE
Add suite of datasets for testing of implementations

### ISSUE THREAD

**Issue by xrotwang** [cldf/cldf#101]
Add here https://github.com/cldf/cldf/tree/master/examples

**Comment by xrotwang** [comment]
See https://github.com/cldf/pycldf/pull/123/commits/763998cd7f710642deb9b4f9c8935b22df1c1413

I'm not sure where the best place for these datasets would be. In https://github.com/cldf/cldf/tree/master/examples I'd like to see rather "real world"examples - not these minimal datasets, with only dummy content.

**Comment by xrotwang** [comment]
See https://github.com/cldf/cldf/blob/master/examples/README.md#examples-for-testing and https://github.com/cldf/cldf/blob/master/examples/README.md#examples-in-the-wild

**Comment by SimonGreenhill** [comment]
great, thanks!
