### ISSUE TITLE
Explicitly state that components are specified via the dc:conformsTo property

### ISSUE THREAD

**Issue by xrotwang** [cldf/cldf#104]

**Comment by HedvigS** [comment]
May I add also including under which conditions components may be missing the dc:conformsTo property or where it may be [set to "null"](https://github.com/glottobank/grambank-cldf/blob/0e814999d7d57f204e3c072e818bb5347b956815/cldf/StructureDataset-metadata.json#L437)?

**Comment by xrotwang** [comment]
Components can never **not** have a `dc:conformsTo` property. Having this property is the very way a component is detected. Other tables may or may not have such a property, but even if they have one, it hopefully wouldn't have a CLDF ontology URI as value.

**Comment by HedvigS** [comment]
Okay, then I don't understand what "component" is 😅 . Are component only things that have a CLDF standard then?

**Comment by xrotwang** [comment]
yes. They are a special kind of tables in the CSVW metadata. The kind where CLDF "knows" what the objects are.

**Comment by xrotwang** [comment]
One of the advantages of using CSVW as underlying metadata model is that we can include arbitrary tables. Thus, we need a way to distinguish the ones we know about (or expect) from additional ones.

**Comment by HedvigS** [comment]
Okay, then I get it. Can things that aren't CLDF-components just not have the dc:conformsTo property then? Just so it's all the same.

**Comment by xrotwang** [comment]
Not really. Say, someone came up with an ontology for archeological data, including a term for a `SiteTable`. I think it should then be possible to add a `SiteTable` to a CLDF dataset, re-using the `dc:conformsTo` mechanism. So as I see it, there's no way around actually inspecting the `dc:conformsTo` value and matching it against known URIs.

**Comment by HedvigS** [comment]
Right. Okay. 

Can things that don't have a dc:conformsTo value appear in the same way?

families.tsv in Grambank has
`   "dc:conformsTo": null,
`
contributors.tsv doesn't have the "dc:conformsTo" at all

**Comment by xrotwang** [comment]
Things that are not components are not really interesting for CLDF. So why would we want to dictate how they should look?

**Comment by HedvigS** [comment]
Sorry, never mind. I thought there was some sort of overhaul going on and since this tripped me up while handling a cldf-dataset I thought it would be good to just make it consistent in cldf-dataset's we make, indeed even if the components aren't cldf that the meta-data json has a certain consistency.

**Comment by xrotwang** [comment]
Consistency is good, but backwards compatibility is more important - at least for a v1.1.

**Comment by HedvigS** [comment]
okay, never mind then. I'll continue coding around it.
