### ISSUE TITLE
Keys not found between tables

### ISSUE THREAD

**Issue by SamPassmore** [cldf/cldf#111]
Hi, 
this is not an issue as such but a question on how solve a problem I have with CLDF. 

I am trying to utilize the CLDF framework for my dataset on a cross-cultural musical dataset (I know, not quite language). 

I have three tables: a Values table (called data; containing the coded data for each song within each soceity), a languages table (called societies; containing metadata on the societies in the dataset) and a table containing metadata on each song 
(called songs; this conforms to a Generic table). 

The song and society tables have foreign keys into the Values table, but currently they don't seem to be pairing up. I get this warning for every foreign key:

`WARNING cldf/data.csv:43784 Key `27479` not found in table societies.csv`

I don't understand how to solve this, since the framework seems to know that it should be looking to match the foreign keys but it can't match any of them. Do you have any advice on how to figure out why cldf validate cannot match the foreign keys? 
My guess is that in one instance they are numbers and the other they are strings, but this doesn't appear to be the case when looking at the raw data. 

Please let me know if more information would help and what that might be. 

Sam

**Comment by LinguList** [comment]
Yes, coordinates are the biggest problem that I have found so far here, you should make sure they are in the right float form, etc.

**Comment by SamPassmore** [comment]
Sorry for the slow reply. Thank-you for the advice. 
I have emailed my collaborators about sharing the data, but am yet to hear back so can't offer you access currently sorry. 

When you refer to coordinates - do you mean latitude and longitude? Or something else. 

I have had some success after checking removing some unwanted characters and commas that might've been misaligning things. But am still have some key errors that shouldn't occur (but no longer all keys). 

I will explore these further and make a new issue if necessary (or send you an email). This new issue is a bit complicated since it correctly identifies some keys as missing, but incorrectly identifies others and I can't figure out why at the moment.

**Comment by SamPassmore** [comment]
I have come across this issue again in a different project. 
The problem I think I am coming across is that when a row has a missing value when it is required, it creates a missing key warning. 

For example: if a languages table is required to have a value in the longitude column but it is missing, I am presented with a warning that longitude is missing. For every language where longitude is missing, I am presented with a missing key warning when looking for that key in forms. 

Maybe this is what @LinguList meant by coordinates. In any case, I am pretty sure that is what is happening, so i thought I'd let you know incase it hadn't been flagged.

**Comment by LinguList** [comment]
You don't need to have a value in coordinates, but if you have a wrong value, it will throw the missing key warning, since the language object then fails and cannot be found in another table.

BTW: do we talk about the kinbank data?

**Comment by SamPassmore** [comment]
Ah ok. So NA would be a wrong value in this case? it should be empty? 

I have two DB I am using CLDF with / and had this problem. 
One is Kinbank yes. The other is a musical database.

**Comment by LinguList** [comment]
You just leave it empty. NA is not a standard value for missing data, as 
there's too much variation (NA, na, NAN, NaN, ...). As a rule, just 
leave it empty.

For kinbank: since the paper presenting the database already appeared, 
and it is impossible to replicate the code reported there by now, I'd 
recommend to put a version on the online database, and archive it with 
Zenodo. If you then link back to the paper, it is easier to Find the 
code, thus accounting for the magic F in FAIR data ;) We can have a look 
if there are current problems in the data in CLDF.

**Comment by SamPassmore** [comment]
The paper hasnt appeared yet (I am still writing it). But yes I will make sure to do that once it is published.

**Comment by xrotwang** [comment]
You can turn `NA` into an acceptable value (meaning `NULL`), if you declare this in the column's `null` property (see https://www.w3.org/ns/csvw#property-definitions). With `pycldf` this could be done  like so
```python
dataset['LanguageTable', 'latitude'].null = ['NA']
```

**Comment by LinguList** [comment]
I meant this one, which has appeared, but no data, right? 
10.1007/s13752-021-00379-6

**Comment by SamPassmore** [comment]
That paper uses Kinbank data, but yes does not come with Kinbank. We have a database paper that details the database structure, descriptive statistics etc. almost ready for submission - citing CLDF obviously. 

The data is public (if you want to look) but we are not drawing attention to it currently because it is going to be restructured on Robert's suggestion: https://github.com/kinbank/kinbank
