### ISSUE TITLE
CLDF extensions

### ISSUE THREAD

**Issue by xrotwang** [cldf/cldf#133]
I propose to add a section about "CLDF extensions" to the CLDF specification. This section would list best practices and recommendations for common usage patterns of CLDF data, which are difficult to fully/formally specify (e.g. because they are referencing commonly used tools which are not under our control - e.g. SQL databases).

Here's the list of extensions I'd like to bring into CLDF 1.2:

- #130 
- #131 
- #132

**Comment by xrotwang** [comment]
@cldf/editors @fmatter @bambooforest @Anaphory What do you think?

**Comment by SimonGreenhill** [comment]
These all sound cool to me 👍

**Comment by Bibiko** [comment]
👍

**Comment by bambooforest** [comment]
Sounds good to me 👍

Nothing for R data frames? 😂

**Comment by xrotwang** [comment]
@bambooforest there's also https://github.com/Robsteranium/csvwr - but both have some limitations, e.g. not working with non-default CSV dialects.

**Comment by chrzyki** [comment]
Sounds good, thanks for putting this together. Very much looking forward to the dataset discovery extension. One question concerning this: Will this be handled via different providers for the different potential sources? Or is the general assumption going to be 'something in an archive format in a remote location'?

And a more general question: These extensions will result in CLDF 1.2. Is the plan going to be that new extension (or set of extensions) -> new minor release?

**Comment by xrotwang** [comment]
I think every change that isn't considered a "bug fix" but keeps backwards compatibility will be released with a new minor release.

**Comment by xrotwang** [comment]
> Sounds good, thanks for putting this together. Very much looking forward to the dataset discovery extension. One question concerning this: Will this be handled via different providers for the different potential sources? Or is the general assumption going to be 'something in an archive format in a remote location'?

will answer at #130

**Comment by xrotwang** [comment]
I started addressing this issue in https://github.com/cldf/cldf/pull/135 
Comments welcome, but please leave in draft status until all issues for milestone 1.2 are addressed.
