### ISSUE TITLE
prerequistes

### ISSUE THREAD

**Issue by Chuterix** [cldf/cldf#144]
how do i setup? setup.py just returns this (i had to install setuptools to get anything working):
`usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied`

**Comment by xrotwang** [comment]
The `setup.py` in this repository is only needed for editorial backoffice tasks. The main purpose of the repos is to host the CLDF spec, i.e. https://github.com/cldf/cldf/blob/master/README.md
