### ISSUE TITLE
Signal grammaticality judgement for examples by linking to a special languoid

### ISSUE THREAD

**Issue by xrotwang** [cldf/cldf#149]
https://github.com/cysouw/pandoc-ling

> Judgment: Examples can optionally have grammaticality judgments, typically symbols like *?! sometimes in superscript relative to the corresponding example. judgements are right-aligned to each other, typically with only minimal space to the left-aligned examples.

**Comment by jcgood** [comment]
I'd like to propose a different solution to this problem. Since ungrammatical sentences are considered to be instances of data that are not actually present in the language being studied, they should not be coded as instances of any language. Rather, they are more like a special register of a language under investigation and could be assigned a special Glottocode like *stan1293 (i.e., "ungrammatical English"). One advantage of this is that an ungrammatical sentence would not then be accidentally harvested as data from a language by a parser that inadvertently ignored a grammaticality column.

**Comment by xrotwang** [comment]
@jcgood I don't think the register of "ungrammatical" languages should be added to Glottolog, but marking examples as ungrammatical by linking them to special languages in the dataset's `LanguageTable` (with empty `Glottocode` column) seems like a good solution.

**Comment by LinguList** [comment]
And one could also add one column in the language table that says upon which model the ungrammatical language is built (e.g., by using the glottocode here).

**Comment by xrotwang** [comment]
> And one could also add one column in the language table that says upon which model the ungrammatical language is built (e.g., by using the glottocode here).

Making this part of CLDF would seem overkill, though. Or do we expect use cases where "all 'ungrammatical English' examples" across datasets are of interest?

**Comment by LinguList** [comment]
I did not mean to make this part of CLDF, but meant to show a simple way to make the relation more explicit. I do not know anyway, how many starred sentences are out there, and what they would be useful for, apart from qualitative discussion.

**Comment by chirila** [comment]
I could imagine cases where ungrammaticality was of interest (where there
is disagreement about it, for example)

On Fri, Dec 15, 2023 at 11:27 AM Johann-Mattis List <
***@***.***> wrote:

> I did not mean to make this part of CLDF, but meant to show a simple way
> to make the relation more explicit. I do not know anyway, how many starred
> sentences are out there, and what they would be useful for, apart from
> qualitative discussion.
>
> —
> Reply to this email directly, view it on GitHub
> <https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcldf%2Fcldf%2Fissues%2F149%23issuecomment-1858146179&data=05%7C02%7Cclaire.bowern%40bulldogs.yale.edu%7Ce4d2a37fb7444fcb8e9008dbfd8ac5a7%7Cdd8cbebb21394df8b4114e3e87abeb5c%7C0%7C0%7C638382544684279944%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=uYeEIo6wY2WrtZ1XR%2B0BdJpLduVJKh3JWn2H%2BypVz5g%3D&reserved=0>,
> or unsubscribe
> <https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAD7SQR2FBI4LAUJRMGPCWKLYJR3AFAVCNFSM6AAAAABAUPQ73KVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQNJYGE2DMMJXHE&data=05%7C02%7Cclaire.bowern%40bulldogs.yale.edu%7Ce4d2a37fb7444fcb8e9008dbfd8ac5a7%7Cdd8cbebb21394df8b4114e3e87abeb5c%7C0%7C0%7C638382544684279944%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=84kwrTTSRxsEA69oobmkIrcTDhOEPb%2B8jKw8sx0cXCM%3D&reserved=0>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>


-- 

Claire Bowern
Professor, Director of Undergraduate Studies
Editor: *Diachronica*
Department of Linguistics, Yale University

**Comment by Glottotopia** [comment]
It is certainly useful to be able to get a list of all ungrammatical sentences from a given languoid, eg when you are building a parser/generator and want to build tests that your engine does not accidentally accept/produce any of them. For this, you want the sentences which are known to be ungrammatical for the languoid you are interested in. 

I like the idea of `*stan1293`. This will fail for everybody who wants to harvest "true" languoid examples.

**Comment by xrotwang** [comment]
But where would the `*stan1293` go? It certainly shouldn't go into the `Glottocode` column, because that's reserved for "proper" Glottocodes. I also remember @jcgood saying that - technically - most non-English sentences would qualify as "un-grammatical English". So I'm not convinced that a use case of the type "harvest all un-grammatical English sentences" is well-defined enough to merit support in CLDF.

If we link un-grammatical sentences to per-dataset-custom languages, possibly called "Ungrammatical English", without linking these dataset-local languages to Glottolog, **and** have a `Is_Ungrammatical` column, we could still support harvesting **all** ungrammatical sentences, and have enough room for non-standard, heuristic determination of the related proper language.

**Comment by Glottotopia** [comment]
one could have a column `intended_language_glottocode`, where one can say that *ich helfe dich* is ungrammatical for Standard German, and that this information is actually relevant for Standard German. The same sentence is also not good Warlpiri (or for 6947 further languages), but that information is not useful for anybody.

**Comment by xrotwang** [comment]
After some reading about (un)grammaticality (e.g. https://en.wikipedia.org/wiki/Grammaticality), I'd lean toward adding a property `ungrammatical`, which - if non-empty - would flag an example as ungrammatical, and would then hold the specific "ungammaticality marker" - `*, **, **, ?, ??, ??` or whatever. A non-empty ungrammaticality property should also be accompanied by linking the example to a special item in `LanguageTable` which is **not** linked to any valid Glottolog language.

AFAIKT, this would support the two main use cases: 
- Excluding ungrammatical sentences for any aggregations of language data and
- providing enough typographical information to format examples as expected.

It wouldn't support the use case of aggregating all examples of "ungrammatical English". As said above, that could still be inferred informally - and I'd like to see cases where this actually happens, before standardizing stuff that isn't actually needed.
