### ISSUE TITLE
Add LGR conformance level column to ExampleTable

### ISSUE THREAD

**Issue by xrotwang** [cldf/cldf#150]

**Comment by Glottotopia** [comment]
what would the possible levels be? For a start, I propose the following: 

- -1: not conformant
- 0: no information 
- 1: same numbers of words in source and gloss guaranteed. This also implies that there are no multiword items in either source or gloss. 
- 2: Words are segmented, and same numbers and types of morphemes in source and gloss guaranteed.  
- 3: differentiated complex meanings: the underscore _ is used as in LGR Rule 4A. The period is not used in these cases. 
- 4: the period is only used for true portmanteau morphemes. All meaning components which have a morphological correspondence are signaled by the means given in LGR rules 4D (Ablaut \\), 4E (Polypersonal > ), 9 (Infixes<>), 10 (Reduplication ~)

**Comment by xrotwang** [comment]
In IMTVault we use two values:
```
$ csvstat -c LGR_Conformance_Level cldf/examples.csv 
  9. "LGR_Conformance_Level"

	Type of data:          Text
	Contains null values:  False
	Unique values:         2
	Longest value:         31, characters
	Most common values:    LGRConformance.MORPHEME_ALIGNED (66932x)
	                       LGRConformance.WORD_ALIGNED (12590x)

Row count: 79522
```
Three, if we count NULL as "no LGR conformance".

**Comment by Glottotopia** [comment]
CLDF can model multiword items, as it splits on tabs, not on spaces. In principle, a user can then substitute all spaces by some other convenient character, like _ or ~, afterwards. 
Still, I think that signalling the presence of whitespace within "words" would be a good idea. The LGR are not 100% explicit, but I believe that whitespace within "words" is an LGR-violation.

**Comment by xrotwang** [comment]
I also think that whitespace within words is an LGR violation. I don't know of many use cases for "multiword items", though. So I'd lean towards signaling "whitespace within words" simply by flagging the sentences as "not LGR conformant".

**Comment by xrotwang** [comment]
@Glottotopia so I would adapt your -1 to 4 conformance levels as follows:
- -1: add as `LGRConformance.NONE` (e.g. whitespace within words or no glosses at all or no correspondence between gloss and words)
- 0: represented by CSVW `null`
- 1:  my `LGRConformance.WORD_ALIGNED`
- 2: my `LGRConformance.MORPHEME_ALIGNED`
- 3: could be added. AFAICT the test would be whether any morpheme gloss contains both, `.` and `_`, correct?
- 4: I'm not sure I'd want to add this because it seems to be the only level that could not be determined automatically. Arguably that would make this level particularly useful, but I'm not sure it can/will be provided consistently enough.

**Comment by Glottotopia** [comment]
>     * 3: could be added. AFAICT the test would be whether any morpheme gloss contains both, `.` and `_`, correct?

presence of _ would be sufficient. But it does not tell us whether the author has been consistent.

> 
>     * 4: I'm not sure I'd want to add this because it seems to be the only level that could not be determined automatically. > Arguably that would make this level particularly useful, but I'm not sure it can/will be provided consistently enough.

again, usage of at least one of \\, >, ~ would indicate that some more sophisticated LGR convention was employed. (< is not needed, as it will always be accompanied by >, which is already checked for). Still, we do not know whether this was applied across the board or not.

I recently had a grammar from a North American languages with glosses such as "He.gave.it.to.her.yesterday.with.good.intentions", where the dot is really overused in my view.

**Comment by xrotwang** [comment]
I guess the question is how we expect this column to be used.

My proposal is some sort of denormalization, i.e. adding something that can be readily computed. The only use of this for may be easier summary statistics (e.g. for IMTVault) or re-use on a platform where there isn't a `pyigt` equivalent to do this computation.

Your proposal is more "meaningful", but would need to be added via some sort of editor/reviewer.

Maybe these to kinds of LGR conformance evaluation should stay separate. E.g. the automated conformance level could be used by editors (in the OTC context) to separate stuff that needs fixing by the author immediately from things that can go under review - to then determine the "meaningful" conformance level. OTOH, maybe the "meaningful" conformance would just be redundant, replicating provenance, i.e. "if its from OTC, it's good, otherwise we don't know".
