### ISSUE TITLE
Alternative translations

### ISSUE THREAD

**Issue by Glottotopia** [cldf/cldf#154]
Suppose you have a text A from the Andes, which has translations into Spanish, English, and Quechua. 

Suppose you have a further text B, which only has a translation into Portuguese. 

Text C has a translation into Russian and into Azerbaijani. 

https://github.com/cldf/cldf/tree/master/components/examples has a field `Translated_Text` and a field `Meta_Language_ID`. 

This setup allows for only one translation language. It is unclear, which language should be chosen if several are available. 

One could have an extra table `Alternative_Translations`, where you get 

```
Text         Sentence_ID  Glottocode  String                                                                                                                    
Text_A.csv   1            stan1288    Todos los seres humanos nacen libres e iguales en dignidad y derechos                  
Text_A.csv   1            cusc1236    Kaytaqa jatun tantakuypi, tukuynin llajtasmanta ujllachasqa runa qhelqerqanku   
```

For consumers downstream, however, it would be good to have one clear place where to look whether a translation into, say, Russian, is available. Having to look for both `Meta_Language_ID` in `examples.csv` as well as for `Glottocode` in `Alternative_Translation` will not be something which will occur to many users.

**Comment by xrotwang** [comment]
I guess, making an `AlternativeTranslation` component part of CLDF might make sense ("explicit is better than implicit" :) ). Alternatively, one could add an `exampleReference` (self-referencing) column to `ExampleTable`, and add alternative translations as "light-weight" sentences, containing only the reference to the "real" sentence and the translation and Meta_Language_ID.

**Comment by xrotwang** [comment]
After a bit more thinking, I'd now lean towards modeling alternative translations as additional, light-weight sentences. I think that's what they actually are. `Meta_Language_ID` does not only refer to the translation language, but also to the language used e.g. for lexical glosses in the `Gloss` line. So for the "full" IGT, one should use the translation language that matches the gloss-language, while alternative translations should repeat the `Primary_Text`, but have empty `Analyzed_Text` and `Gloss` columns (and link to the full entry using `exampleReference`).

While this would mean that naively estimating corpus size by counting sentences wouldn't work anymore, it allows us to treat alternative translations in the current framework.

**Comment by Glottotopia** [comment]
should the table `alternative_translations.csv` redundantly include the "main translation" as well? Since we are going towards denormalization anyway, this might be a comfort feature for some users.

**Comment by xrotwang** [comment]
> should the table `alternative_translations.csv` redundantly include the "main translation" as well? Since we are going towards denormalization anyway, this might be a comfort feature for some users.

What I'm leaning towards now is **not** have a `alternative_translations.csv` table at all, but list the alternative translations as additional sentences - ones without gloss and linked to the "full" entry with a foreign key.

**Comment by Glottotopia** [comment]
like this?

```
1  Veni  I came       stan1293
2  Vidi  I saw        stan1293
3  Vici  I conquered  stan1293
?  NULL  Ich kam      stan1295  1
?  NULL  Ich sah      stan1295  2
?  NULL  Ich siegte   stan1295  3
```

**Comment by xrotwang** [comment]
Yes, basically. Although I would repeat the primary text:
```
1         Veni vidi vici    ANALYZED    GLOSS    I came I saw I conquered    stan1293
2    1    Veni vidi vici    NULL        NULL     I kam ich sah ich siegte    stan1295
```

**Comment by xrotwang** [comment]
With more mnemonic sugar you'd use IDs like `1-en` and `1-de`, I guess.

**Comment by Glottotopia** [comment]
could you redo this for the 6-line table above, where "veni", "vidi" and "vici" are all sentences of their own, with linearity? I suspect the final table to be very confusing.

**Comment by xrotwang** [comment]
```
1  Veni  I came       stan1293    ANALYSZED GLOSS
2  Vidi  I saw        stan1293    ANALYZED GLOSS
3  Vici  I conquered  stan1293    ANALYZED GLOSS
4  Veni  Ich kam      stan1295  1
5  Vidi  Ich sah      stan1295  2
6  Vici  Ich siegte   stan1295  3
```

**Comment by xrotwang** [comment]
See https://github.com/cldf/cldf/tree/master/modules/TextCorpus#alternative-translations
