### ISSUE TITLE
Zenodo release doesn't actually contain a zip file

### ISSUE THREAD

**Issue by johenglisch** [cldf/cldf#158]
The [Zenodo release](https://zenodo.org/records/10548119) appears to be corrupted.  The ‘zip’ file in the repo is a json file with the following content:

    {
       "documentation_url" : "https://docs.github.com/rest/repos/contents#download-a-repository-archive-zip",
       "message" : "'v1.3' has multiple possibilities: https://github.com/cldf/cldf/zipball/refs/heads/v1.3, https://github.com/cldf/cldf/zipball/refs/tags/v1.3"
    }

(Thanks to Brad Taylor for pointing this out.)

From the look of it it seems like GitHub was confused because this repo has a branch and a tag, which are both named `v1.3`.

I checked some other recent data releases, just in case (<https://zenodo.org/records/10555859>, <https://zenodo.org/records/10555488>, <https://zenodo.org/records/10495417>).  They're not affected.

**Comment by xrotwang** [comment]
Just published a bugfix release: https://zenodo.org/records/10579537
For some reason, the DOI doesn't resolve yet, though. Hope this is a temporary issue ...
