### ISSUE TITLE
Specify MediaTable component

### ISSUE THREAD

**Issue by xrotwang** [cldf/cldf#33]
Media files should be referenced via URI, which would allow to even include them directly using [data URIs](https://en.wikipedia.org/wiki/Data_URI_scheme).

In addition to the `MediaTable` component, we'd need a `mediaReference` property in the ontology.

The CLDF `name` property - if assigned to a column in a media table - is interpreted as filename, thus can be used to derive a filename extension, etc. alternatively, this can be derived from the return value of `Dataset.get_row_url(...)`.

**Comment by xrotwang** [comment]
@Bibiko you might be in the best position to specify this component, considering that it should support the soundcomparisons use case.

**Comment by xrotwang** [comment]
Dictionaria datasets have a table `media.csv`, which could serve as inspiration: https://github.com/dictionaria/diidxaza/blob/master/cldf/media.csv

**Comment by xrotwang** [comment]
Here's an example of another dataset which could be turned into a CLDF dataset with a media table:
https://dataverse.no/file.xhtml?persistentId=doi:10.18710/IORWF6/DBE696&version=1.0

**Comment by xrotwang** [comment]
To make it possible to derive a URL for a media file without unnecessarily increasing the file size of the CSV table, `MediaTable` should specify a `valueUrl` property on the `ID` column **or** a column of CSVW datatype [anyURI](https://github.com/cldf/csvw/blob/84dc47062e6f9db6cc061b39c9211be440ff02ac/src/csvw/datatypes.py#L81).

**Comment by xrotwang** [comment]
So something along the lines of
```python
from csvw.datatypes import anyURI

class Dataset:
    def get_url(self, row, table):
        id_col = None
        for col in ds[table].tableSchema.columns:
            if col.datatype.base == anyURI.__name__:
                return row[col.name]
            elif str(col.propertyUrl) == 'http://cldf.clld.org/v1.0/terms.rdf#id':
                id_col = col
        assert id_col, 'no ID column found in table {}'.format(table)
        return id_col.valueUrl.expand(**row)
```

**Comment by xrotwang** [comment]
@Bibiko @SimonGreenhill @chrzyki @LinguList could you review this: https://github.com/cldf/cldf/pull/105/commits/e8507351a6ea15247d5f7dd833895f1403327b96

**Comment by Bibiko** [comment]
I only found two tiny typos, otherwise it sounds coherent
