### ISSUE TITLE
It is unclear (also from pycldf implementation) whether metadatafree datasets may have additional columns

### ISSUE THREAD

**Issue by Anaphory** [cldf/cldf#46]
Followup on https://github.com/cldf/pycldf/issues/50 from the formal side:

The specs state that
> A dataset can be CLDF conformant without providing a separate metadata description file. To do so, the dataset must follow the default specification for the appropriate module regarding
> - file names
> - CSV dialect
> - column names
> exactly. Thus, rather than not having any metadata, the dataset does not specify any; and instead falls back to using the defaults, i.e. "free" as in "beer" not as in "gluten-free".

A close reading of that seems to imply that additional columns outside those defined in the corresponding module `.json` should not be permitted.

However, several other bits of the specs (including the `Wordlists.md` with its talk about optional columns) give me the impression that additional columns should be permitted, and `cldf validate` does not complain, either.

**Comment by xrotwang** [comment]
Agree. Would changing "column names" into "required column names" do?

**Comment by Anaphory** [comment]
I think I'd write it in there explicitly, like
> The CSV file may contain additional columns not specified in the default module descriptions. CLDF tools may handle these columns as named columns of datatype `string` with no `propertyURL`, or they may ignore these columns, or expose them in some contexts but not in others.

**Comment by xrotwang** [comment]
@Anaphory I'll add the first part of your suggestion, but not the second, since I think when CLDF tools make use of any non-standard columns, they are off in non-CLDF territory and I wouldn't want to prescribe any behaviour there :)
