### ISSUE TITLE
Splitting/merging files in CLDF

### ISSUE THREAD

**Issue by cysouw** [cldf/cldf#47]
**Proposal**

Depending on the data, it is sometimes easier to add multiple datasets into a single file, and use a specific column to mark the different datasets. For example, one might either make a different alignment file for each cognate set, or one might combine many different alignment into one file and add a column like "COGNATE ID". Both options have their use-cases. For example, in dialect data with thousands of cognates for a specific meaning it often maked more sense to  make separate files for each cognateset.

It is of course even possible to mix and match those two options, i.e. splitting data into different files in some situations, but using internal separation into groups in other files.

I could not find any mentioning of this in https://www.w3.org/TR/tabular-metadata/ (maybe it is too trivial?). It might make sense for CLDF to specify either:

- to always merge files with identical structure into one file (which might lead to very large files: I have actual use-cases that easily lead to files of multiple GB)
- to always split files into subsets (which might lead to very many files: I have use cases that lead to ten-thousands of files)
- allow both approaches and specify for the many-files usage to make sub-directories in a CLDF-directory named according to the component, e.g. a sub-directory `cognates` with many files for the different cognatesets. (which I would propose)

Note that this decision for the CLDF is independent of the practical work with those files, as it should be trivial to either merge multiple files into one or to split a large files into many separate files.

Should I add something about this to the section "Data Files" in the `readme.md`?

**Comment by cysouw** [comment]
**Question**

One practical consideration is the following: when splitting a dataset into many different files, do we need unique identifiers across all files? Or might it be sufficient to refer by the combination of filename and identifier (thus only needing unique identifiers within each file)? We might propose to force unique identifiers by building them explicitly from filename+identifier. In that way we are independent from the split-up into files. This seems to be the approach taken in the [CLDF download of WALS](http://wals.info/download).

**Comment by cysouw** [comment]
**Question**

A more involved option is the following: I have large files which are split up according to a specific property, so each file would have a column that would be the same in the whole file. For example, each file is a single cognate set with thousands of lines with cognates (e.g. from dialects). Now, the consistent way to mark this is to add a column in each file that repeats the same information thousands of time. This is cumbersome, but of course the easiest way to handle things, because merging of files becomes trivial. This seems to be the approach taken in the [CLDF download of WALS](http://wals.info/download).

However, would it maybe be a good idea to allow for some simplification in such situations? For example by adding a `mergeTable` indicating which information is identical in each individual file in a directory? Or is this just needlessly complex, and not worth the space-saving?

**Comment by cysouw** [comment]
I just found [this](https://github.com/cysouw/cldf/blob/master/faq.md#frequently-asked-questions) in the FAQ, so the second question is answered: yes, it is possible to have a 'virtual column' in the metadata to abbreviate information that is identical in whole files.

**Comment by xrotwang** [comment]
The [spec says that each component may only be present once per dataset](https://github.com/cldf/cldf/blob/master/README.md#cldf-components) - although possibly not clearly enough. So regarding @cysouw's proposal: We specify to always merge data of the same type into one file. This is particularly important, because otherwise processing of foreign key relations, which are implicit in the data model, becomes more difficult.

**Comment by xrotwang** [comment]
As a corollary of the "always merge" theorem it follows that identifiers are always component-wide unique per dataset.

**Comment by cysouw** [comment]
The problem though is that I will come up with files of 5 GB or more in my data. Actually, I just tried to estimate an even larger dataset that I at some point would like to put into CLDF, and that might reach 30 GB. Wouldn't that be a problem?

Yet, I agree about the unique identifiers: they should probably better not depend on file names (that will lead to problems too easily).

However, when every line has an unique ID, then we could just simply allow the data to be split into different files, just for practical reason, isn't it?

**Comment by xrotwang** [comment]
@cysouw How do you end up with 30 GB files - assuming the data is purely textual? If it is because you have many columns, this could be dealt with by additional tables with a one-to-one correspondence to the main file.
If it is because you have many rows, this may be a problem. I have a hard time, though, accepting that multiple datasets won't be a solution. If you want to analyse the data together, you still have the mechanism built-in to pycldf which lets you throw multiple datasets into one sqlite db. And 30 GB shouldn't be a problem there.

I think generally, the "data in text files" idea breaks down at a certain amount of raw data.

**Comment by cysouw** [comment]
@xrotwang I did an alignment of 77 bible translations, and the full alignments are [here](https://github.com/cysouw/multialignment-of-paralleltext), look at the directory `alignments`. This directory is 1.12 GB large, and it will become even bigger when all necessary columns are included. This directory would become one file `functionalEquivalentsTable`.

Ideally I would like to do this for all 1850 bible translations that I currently have. Trying to estimate the end result, I'll get to about 30 GB.

Also, the raw texts of my parallel text corpus is about 4 GB. I now have is separated into one file per translations, so it is about 1850 files. Interpreting it as a `formTable` (which it is!), adding all the necessary columns, I would easily get to about 5 GB.

Now, all these files are easy to zip, so the file size itself is probably not a problem. However, reading them into memory will quickly lead to problems. I think we should not allow datafiles bigger than about 1GB (or even smaller)

**Comment by xrotwang** [comment]
Yes, reading 30 GB into memory will typically lead to problems. But this will be true in both cases: 30 * 1 GB files or one 30 GB file. So if you want to analyse this amount of data you have to be smarter than reading it in memory anyway. I outlined one way of doing this above: See whether you can split the data into multiple CLDF datasets and merge them in sqlite - using functionality already present in pycldf.

**Comment by cysouw** [comment]
Another option (which I was think of) is to have a 'lazy' reader of the data for such cases, in which the structure of the data is read, but the actual data is not read into memory. Only at using the data the relevant parts will be read, and might have to be discarded afterwards. This makes things a bit more complex, but only for those user who want to use such large datasets (me :-)).

Again, I don't see a problem in allowing a directory with files instead of a single file. By default it should simply be a `cat` operation to put them all together.

**Comment by xrotwang** [comment]
Splitting what is logically one table into a couple of CSV files is problematic, because this makes it impossible to add foreign key constraints referencing rows in this table.

**Comment by xrotwang** [comment]
Nowhere in the specification do we say anything about how CLDF should be processed. Whether reading everything into memory is an option, depends a lot on your local configuration after all. I'd say we close this issue.

**Comment by xrotwang** [comment]
@cysouw feel free to re-open when you still think this is necessary and have a solution for the foreign key problem.

**Comment by cysouw** [comment]
So it would be fine to allow the following, even for metadata-free conformance? Then I would add it to the `readme`:

---

Any data table in the CLDF can be subdivided into separate files (e.g. because of large size of the complete table) as long as:

- the table structure is identical in all files (i.e. exactly the same columns and column names are used)
- each row has an unique identifier (so no identifier is repeated across different files)
- all files are put in a directory with the name of the CLDF table (e.g. a directory `forms`)

In effect, such a separation of files is just for practical reasons. Logically all files concatenated into one file would have exactly the same structure.

**Comment by xrotwang** [comment]
No, I don't think this works. According to the [CSVW spec](http://w3c.github.io/csvw/metadata/#foreign-key-reference-between-tables) the `resource` attribute of the target spec of a foreign key must point to one CSV file.

I really think this should not be part of the CLDF spec. It would raise the bar for tools implementing the spec, and in particular raise the expectation that all tools should handle these edge cases of huge data files.

**Comment by cysouw** [comment]
What about [this](http://w3c.github.io/csvw/metadata/#schemas):

> A schema is a definition of a tabular format that may be common to multiple tables. For example, multiple tables from different sources may have the same columns and be designed such that they can be aggregated together.

Such aggregation seems to be what I'm envisioning.

Please note: I'm fine with not including this in metadata-free conformance, but I would like to know how to do this in extended conformance, as I will definitely need this for my data.

**Comment by xrotwang** [comment]
You didn't answer to my suggestion for a workaround on your end: Splitting your data into multiple datasets.

**Comment by cysouw** [comment]
well, I could make 1850 different CLDF datasets, all with exactly the same structure (one for each text). This works for the raw data, but not for combined analyses (e.g. functionalEquivalents): they necessarily go across all those datasets. I don't think I see any sensible way to cut them into different datasets.

I found [this](http://w3c.github.io/csvw/use-cases-and-requirements/#R-CsvAsSubsetOfLargerDataset) in the use-cases for the CSVW spec.

**Comment by xrotwang** [comment]
Unfortunately, a csvw schema does not seem to be the solution to the foreign key problem. The description of the `schemaReference` attribute says

> A link property holding a URL that is the identifier for a schema that is being referenced. If this property is present then resource MUST NOT be present. The table group MUST contain a table with a tableSchema having a @id that is identical to the expanded value of this property, and there MUST NOT be more than one such table. That table is the referenced table.

So, we still end up with exactly one table, hence exactly one `url` specifying the location of the CSV file.

Also, e.g. our `csvw` package doesn't support schemas (yet?), since this would come at a pretty hefty price, namely implementing support for `@id`s and expanding URL properties.

I'd say let the files grow big, and cut them to pieces (or stream to sqlite) for analysis. Once we start worrying about file size, we will at some point have to worry about number of files per directory ...

**Comment by cysouw** [comment]
Just to clear up all possible misunderstanding, I have made an example of what I thought should be possible. @xrotwang could you have a look whether this really breaks? It seems so simple and obvious to me.

[multifileCLDFtest.zip](https://github.com/cldf/cldf/files/1505482/multifileCLDFtest.zip)

**Comment by xrotwang** [comment]
See [5.4. Tables](http://w3c.github.io/csvw/metadata/#tables)

> url
>    This link property gives **the single URL** of the CSV file that the table is held in, relative to the location of the metadata document

**Comment by cysouw** [comment]
first: [5.1.2 Link Properties](http://w3c.github.io/csvw/metadata/#dfn-link-property) also seem to allow directories.

and then: [6 Processing Tables](http://w3c.github.io/csvw/syntax/#processing-tables) gives an explicit example of a schema being applied to multiple tables at once.

This seems indeed contradictory. Maybe each `url` only specifies one link, but there can be more than one `url` properties?

again: I'm perfectly fine with this not being default CLDF (i.e. metadata-free conformance), but it seems completely in line with the CSVW-spec to me...

**Comment by xrotwang** [comment]
Link Properties may allow URLs that look like they may point to a directory, but that's irrelevant. They still only resolve to one response, with no specified mechanism to handle the equivalent of "index.html".

In section 6, the example has more than one table - each with one `url`. And from my reading of foreign keys, such a configuration would not be valid as target of a foreign key.

**Comment by cysouw** [comment]
In the end, this seems to be about the URL (that should not go to a directory, but to a file where to find the key). There might to be a solution in [URI-templates](http://w3c.github.io/csvw/metadata/#uri-template-properties), e.g. [rfc6570](https://tools.ietf.org/html/rfc6570), but I'll have to think more about that.
