### ISSUE TITLE
Chunking of strings

### ISSUE THREAD

**Issue by cysouw** [cldf/cldf#48]
**Questions**

Within strings in a cell in a CSV-file, it is possible to use specific symbols to specify chunking of the string. The explanation [in the FAQ](https://github.com/cysouw/cldf/blob/master/faq.md) is either badly formulated or confused. Or maybe I am confused :-).

The given example there is the following:

```
A third level of structured content can be achieved for cells of datatype string by specifying a regular expression which the values of a cell must match. E.g. the following column specification

{
    "name": "segments",
    "separator": "+",
    "datatype": {
        "base": "string",
        "format": "([\\S]+)( [\\S]+)*"
    }
}

This will make sure cell content of the form `abc def+geh` can be split into the nested lists `[['abc', 'def'], ['geh']]`.
```

In my understanding, this describes the plus sign as a *secondary* separator, and within each of the substrings there is an optional space (which is not defined as a separator in this simple example yet, it is just implicitly assumed in the regex). Just this declaration would analyse the string `abc def+geh` into `['abc def', 'geh']`.

Actually, for the a tertiary separator to work, it would need something like this (I doubt that this is formally correct: please improve if necessary!):

```
{
    "name": "primary segments",
    "separator": "+",
    "datatype": {
        "base": "string",
        "format": "([\\S]+)( [\\S]+)*"
    }
    {
        "name": "secondary segments",
        "separator": " ",
        "datatype": "string"
    }
}
```

With this description the string `abc def+geh` will be split into the nested lists `[['abc', 'def'], ['geh']]`.

When I'm not confused, I'll slightly reformulate the FAQ.

**Comment by xrotwang** [comment]
The FAQ is meant as a how-to for cases in need of a tertiary separator. That's why it says "the column specification will make sure cell content [...] can be split", rather than "will be read as nested lists". So while the secondary separator comes with tool support, e.g. in pycldf, the tertiary separator is up to the user. The regex is just a way to at least get tool support for validation, if not for parsing.

**Comment by cysouw** [comment]
OK, so no tertiary separators in CLDF then!

As a user in a private workflow you can of course do what you want :-)
