### ISSUE TITLE
Slicing, indexing, subsetting: counting!

### ISSUE THREAD

**Issue by cysouw** [cldf/cldf#49]
**Proposal**

Concerning `slicing` as used [here](https://github.com/cysouw/cldf/tree/master/components/partialcognates):

This is yet another "tab vs. comma" discussion, as there are at least two different approaches to counting: first the slicing from Python/C, where the counter starts at zero and the end is not included (basically you are counting boundaries here), and second the indexing/subsetting from Matlab/R, where the counter starts at one and the end is included (basically you are counting elements here).

Please note: I am perfectly aware that the two approach are equivalent, and I also know that this is very much a question of what you are used to. The crucial point is which approach will more quickly lead to misunderstanding when somebody uses the data without reading the documentation.

I think it important to realize that the CLDF is not a programming language, but a data description. So, it should be easily understandable for people outside a particular coding framework. I think that the 'element-counting' Matlab/R approach is *much* easier to grasp intuitively than the 'boundary-counting' Python/C approach.

If you have seven elements (with six explicit boundaries coded in the data), and you want to refer to the third element, then using "3" seems more natural than using "2:3". The same if you want to refer to elements 1 through 4, then "1:4" seems more natural than "0:4" (the more so as the boundary at "0" does not exist in the data).

So: my proposal is to not use "slicing" but "element counting" in the CLDF.

**Comment by cysouw** [comment]
**Question**

The only use case of slicing at the moment seems to be the component [`partialcognates`](https://github.com/cysouw/cldf/blob/master/components/partialcognates/PartialCognateTable-metadata.json). This table-structure is not completely clear to me; I think there is something missing. Or maybe I am confused :-)

The problem is that it is not clear to which data the slice refers. The intention here is that the slice refers to the `form` as references by the `Form_ID`. As noted in the readme, this `form` needs to have a separator specified in the `FormTable`.

Somehow it needs to be made explicit that the slice refers to the `form` as references by the `Form_ID`. Where should this be specified? Should a slice maybe always, everywhere in the CLDF, refer to `Form_ID`?

**Comment by LinguList** [comment]
No, the slice refers to "segments". Forms don't mean anything here.

**Comment by LinguList** [comment]
Sorry, I forgot that we had a discussion on this: @xrotwang argued, if I'm not mistaken, that it could also be "form" that is sliced. In all usecases for partial cognates that I provided data for, however, it was based on "Segments", as we also provided alignments for partial cognates.

**Comment by xrotwang** [comment]
I agree that slices are somewhat ill specified, which leads to confusion what they refer to. I think Slice should rather be a [derived datatype](http://w3c.github.io/csvw/metadata/#derived-datatypes) than a [property](http://cldf.clld.org/v1.0/terms.rdf#slice), and the slice specifying the segments relevant for a partial cognate should be an explicit property instead.

**Comment by xrotwang** [comment]
Regarding the question of zero-based indices: We use Python's slice notation not only because it has appropriate semantics, but also because it is well documented - and potentially already known. Using half of it (the `:` separating indices), but not the whole thing (zero-based indices), seems to me a worse trade-off.

**Comment by LinguList** [comment]
BTW, when just re-reading the description on partial cognates, it is clear that we define them, es I initially thought, only for segments. For me that makes most sense: we could think of a dataset in orthography where partial cognacy is annotated in the same way, but I would not like to encourage people to do that, as segmentation and alignments are the key to keep these judgments transparent, at least from a linguistic perspective.

**Comment by cysouw** [comment]
[Matlab](https://de.mathworks.com/help/matlab/ref/colon.html) and [R](https://www.rdocumentation.org/packages/base/versions/3.4.1/topics/Colon) also use the colon, but the numbers to either side are elements, not boundaries.

So, the colon is used widespread for ranges, that is no problem. The question is whether the number should be elements or boundaries. I would strongly favour elements.

**Comment by xrotwang** [comment]
@cysouw  I take the point about the colon. Reading the R documentation it seems the syntax isn't as powerful as Python slices, though, e.g. there's no optional third step component as in
```python
>>> list(range(10))[3:9:2]
[3, 5, 7]
```

**Comment by cysouw** [comment]
@xrotwang indeed, in R you'll need the function [`seq`](https://www.rdocumentation.org/packages/base/versions/3.4.1/topics/seq) for that.

However, that is completely irrelevant for the discussion here :-). In CLDF we will not use such sequences anyway. We will always have to be explicit, so `3 5 7 9` instead of `[3:9:2]`.

BTW: the current spec uses space as separator in slices (as I did above). I'm fine with that, but is there any reason not to use a comma?

**Comment by xrotwang** [comment]
I'm not sure the step component in slices will never be useful. If we think of slice as a derived datatype, it would be generally applicable. I.e. CSVW basically gives us a way to have lists in cells of csv data, and slices gives us a way to reference - well - slices thereof. Given the generality of this, I certainly think more expressiveness is better.

**Comment by xrotwang** [comment]
The reason to use space as separator between strings is that Python's `split` method, when invoked with no arguments, will split on whitespace. So basically
```python
>>> 'a b c d'.split()
['a', 'b', 'c', 'd']
```
vs.
```python
>>> 'a,b,c,d'.split(',')
['a', 'b', 'c', 'd']

```

**Comment by xrotwang** [comment]
When I said above that choosing python's slices as blue-print was also due to this being well documented, this was still not the whole story. I basically would like to point to python as the reference implementation of this part of the spec. In this way CLDF does become a bit of a programming language.

**Comment by cysouw** [comment]
Then my proposal would be the following for the ontology (note that we have to change the regex too!)

```
<rdf:Property rdf:about="http://cldf.clld.org/v1.0/terms.rdf#slice" dc:type="generic-property">
    <rdfs:label xml:lang="en">Slice</rdfs:label>
    <rdfs:comment rdf:parseType="Literal">
        <p>Slice specification following the Matlab colon notation documented here: https://de.mathworks.com/help/matlab/ref/colon.html</p>. This slice refers to elements in a list (like Matlab/R) and not to boundaries between the elements in a list (like Python/C). So the slice '2:4' from a list [1,3,5,7,9] refers to the elements [3,5,7] and not [5,7].
    </rdfs:comment>
    <csvw:name>"Slice"</csvw:name>
    <csvw:datatype>{"base": "string", "format": "\\d+(:\\d+){0,2}"}</csvw:datatype>
    <csvw:separator>" "</csvw:separator>
</rdf:Property>
```

**Comment by xrotwang** [comment]
Ok, I'm willing to cave in to switching to 1-based indexing. But I would drop support for a third component specifying the increment, because Matlab has this as **second** component while in Python slices it's **third**. This would allow for too much confusiuon, I think.

**Comment by LinguList** [comment]
This essentially means that we need to re-do the code that we did for our Hill-List paper, where we introduced the slicing the first time, including conversion to cldf in lingpy-2.6.1 just published. I just want all to be aware that at some point we need to get starting with things and not discuss too long about some things that basically work but just do not express the basic look and feel we may know from our home software. E.g., I was against slicing in the beginning, as I used integers as identifiers, as it is still the case in LingPy / EDICTOR, but @xrotwang convinced me of the broader use of slices. I'm fine writing an update, but I think it is really time that we settle some things, and not get lost in discussions which are in my opinion not about the functionality (which is important) but about the look-and-feel (which is not important).

**Comment by xrotwang** [comment]
Ah, right. I agree with @LinguList; considering that the amount of CLDF data out there will never be huge, we should take care not to render what's there an inconsistent mess. @cysouw if you still think this is an important issue, feel free to re-open and assign to milestone CLDF 2.0 - which would be the next release allowing for backwards incompatible changes.

**Comment by xrotwang** [comment]
@LinguList I looked at the data of the paper and this seems to be pre-CLDF-1.0 in various other regards as well, so re-creating the data may be a good idea. Did you talk about the slice notation specifically in the paper?

**Comment by xrotwang** [comment]
Btw. what I find most compelling @cysouw's proposal is the fact, that if you don't actually use slice notation (i.e. no colon), the notation of multi-slices just reverts to integer, 1-based indices (which is what EDICTOR used before, right?); e.g.
```
"2:5 7:9" == "2 3 4 5 7 8 9"
```

**Comment by cysouw** [comment]
@LinguList I feel with you! I still haven't publish my data because I am constantly changing formats, software, descriptions, etc. And you are right, at some point we should simply go ahead and do things. However, there will be some backward-incompatibility at some point, as always...

Regarding this point: There are two issues here:

- the first is whether to use `element counting`, which it seems now that we all three agree is the best way to go.
- the second is the colon operator, which is actually just a shortcut. For reasons of simplicity I would be willing to leave out the colon, and force people to name all element explicitly (as @xrotwang noted, the Matlab structure of the colon operator is every so slightly different from the Python structure, which might lead to even more confusion, which I didn't realise).
- If we go with `element counting` and we do not allow the colon operator, then the term `slicing` might be misleading, because it is strongly entrenched in the Python community.

So maybe we should complete redo this :-)

- call it `counter` instead of `slice`
- use `element counting` instead of `boundary counting`
- only allow space-separated lists of integers (no colon)

**Comment by LinguList** [comment]
@xrotwang, since EDICTOR/LingPy need flat files, the notation is:

id | tokens  | cogids
--- | --- | ---
1 | a + b + c | 1 2 3
2 | b + c | 2 3
3 | a | 1

So this just allows us to link the forms, as we do with cognate set identifiers, but this time specifically tight to order of the tokens. The Hill+List paper anyway needs a revision, and LingPy-2.6.1 should also conform to cldf1.0, so we'll have to update there to. My major concern was that changing too much will just slow us down, we need to make some compromises, otherwise we won't get anything done.

But with your milestone and the time plan, this is all fine with me, and I think, it'll even be less work to update, as we only have to adjust lingpy this time (and lexibank, if we're not careful), and we can then use LingPy to update the code in the Hill-List paper. I did not yet check with CLICS and pyclics, but I assume that most things should also be covered.

**Comment by xrotwang** [comment]
@LinguList just added one more issue: #61 That's ok, too, right?

**Comment by cysouw** [comment]
@LinguList I just looked into more detail in the data from the Hill+List paper, and I noticed that you use spaces around the plus symbol. I think there should be no spaces there.

**Comment by xrotwang** [comment]
@cysouw When you say "counting", wouldn't "enumerating" be more appropriate?

**Comment by cysouw** [comment]
I'm perfectly fine with "enumerating"

**Comment by LinguList** [comment]
> @LinguList I just looked into more detail in the data from the Hill+List paper, and I noticed that you use spaces around the plus symbol. I think there should be no spaces there.

I discussed this before with @xrotwang, and while I could remove the spaces, I don't agree with it, as, the primary segmentation of the sequence is just by space, and the secondary is by the plus. This is how it is handled in EDICTOR and LingPy. We can give it up for cldf, but here, I really think that it is aesthetically much more pleasing to think of a sound sequence which is secondarily segmented. E.g., in orthography profiles, your output for a word with spaces is also not:

```
h au s#m ei s t e r
```
but instead
```
h au s # m ei s t e r
```

Since it is possible to deal with secondary segmentation through orthography profiles, this would overcomplicate the code to an extreme degree, as you'd need to capture all instances where you have, say, the dash in the source and the characters before. So: no, it needs to split on ``` + ``` with two spaces left and right.

**Comment by cysouw** [comment]
Maybe you should just specify `"separator": " # "` with the spaces included?

**Comment by LinguList** [comment]
right, that would be my intention, and I think we even agreed on this with @xrotwang before, but it is already some time ago, and I didn't work with cldf parts until then.

**Comment by cysouw** [comment]
ah, no: such a specification should be in your metadata, not in the default CLDF. Partial cognacy can also exist without space-based alignment.

**Comment by LinguList** [comment]
give an example, please.

**Comment by cysouw** [comment]
If I just want to record the statement that parts of German `Autotür` and Dutch `Huisdeur` are cognate, I could use the following, without yet going into the alignment:

```
LANG      FORM         ENUM   COGNATESET_ID
german    Auto+tür     2      DOOR1             
dutch     Huis+deur    2      DOOR1
```

**Comment by LinguList** [comment]
yes, we had that discussion in the past, but I argued, and I still argue that nobody who does partial cognates and really means it seriously with linguistics, would do that based on orthography. And all examples that are out there, have the alignments shipped avec. We even define the segment_slice for the segments, so this is fully consistent with the requirement, and if something else is needed, I think the people who should specify their metadata are the ones who dare to propose partial cognates without proposing alignments of segments.
