### ISSUE TITLE
Annotation of secondary columns

### ISSUE THREAD

**Issue by cysouw** [cldf/cldf#51]
**Proposal**

Given a column in a CSV-file that uses secondary separators, sometimes these separated parts will be aligned, i.e. each string has the same number of chunks, and the chunks have some kind of equivalent status in each row. Such an multi-alignment is for example used in the component `cognates`.

In such a situation I would like to be able to refer to such a column to add extra information to such a column. This might be solved by adding a `alignmentAnnotationTable` to the CLDF.

- representation in standard orthography (STANDARD)
- mark columns as uninteresting for further analysis, because the data is not consistently encoded (IGNORE)
- mark sets of columns as "identical", which is necessary in case of metathesis (MERGE)
- mark sets of columns as "complex segment", which happens in situations like a multi-alignment of Germanic `school`: It is probably best to align two columns for the onset here (with languages having /sk/ or /sx/), but in some languages these two columns are merged into one (e.g. /ʃ/). (COMPLEX)
- etcetera

Technically it not problematic to make such annotations using column counting/slicing, for example like this:

```
{
    "url": "alignmentAnnotation.csv", 
    "dc:conformsTo": "TODO", 
    "tableSchema": {
        "columns": [
            {
                "name": "ID", 
                "required": true, 
                "propertyUrl": "http://cldf.clld.org/v1.0/terms.rdf#id", 
                "datatype": {
                    "base": "string", 
                    "format": "[a-zA-Z0-9_\\-]+"
                }
            }, 
            {
                "name": "Form_ID", 
                "required": true, 
                "propertyUrl": "http://cldf.clld.org/v1.0/terms.rdf#formReference", 
                "datatype": "string"
            }, 
            {
                "name": "Slice/Count", 
                "required": true, 
                "propertyUrl": "http://cldf.clld.org/v1.0/terms.rdf#slice", 
                "datatype": {
                    "base": "string", 
                    "format": "\\d+(:\\d+)?"
                }, 
                "separator": ","
            }, 
            {
                "name": "AnnotationKind", 
                "required": true, 
                "propertyUrl": "TODO", 
                "datatype": "string"
            }
            {
                "name": "AnnotationContent", 
                "required": false, 
                "propertyUrl": "TODO", 
                "datatype": "string"
            }
        ]
    }
}
```

Examples of the kind of information that I would like to add to each column are the following (see for example [here](https://github.com/cysouw/PAD/blob/master/alignments/corrected/Aepfelchen_1003.msa), though note that this is not according to CLDF yet!).

**Comment by cysouw** [comment]
**Question**

As can be seen in the example of alignment annotation [here](https://github.com/cysouw/PAD/blob/master/alignments/corrected/Aepfelchen_1003.msa), in practice it is much easier to add such annotations as lines in a `cognatesTable`. Such lines are of course of a complete different kind, so they do not belong to a `cognateTable`. 

Can we include such an alternative representation to the CLDF, or should we leave such a formatting to individual workflows, forcing annotations in the CLDF to the more cumbersome format proposed above.

**Comment by cysouw** [comment]
**Question**

For some kind of annotations there is no `AnnotationContent` but only an `AnnotationKind`(like IGNORE for ignoring columns or COMPLEX to indicate that some columns belong to a complex segment). Can we just leave some information empty in such cases? Cf.

**Comment by xrotwang** [comment]
I can see how this is useful. One guiding principle I like to use for whether something should be included in the spec is the question of tool support. By piggy-backing on the CSVW spec, we can already include all sorts of additional tables (what you refer to by "individual workflows", right?).

Now, "tool support" isn't really clear-cut, because for me, the tool supporting a particular component may often only be `clld`, i.e. a tool to publish the dataset, not one to analyse the data. So, I guess I'm open to discuss further :)

**Comment by cysouw** [comment]
OK. I'll just start using this, and when I have a finished example, I'll post a pull request!

As for tool support: I'm actually working to get my R-package `qlcData` to support this kind of data, so there will be more in the future!

**Comment by xrotwang** [comment]
Will re-open, if need arises again and some sort of implementation supporting this is available.
