### ISSUE TITLE
segmentsSlice should be a property in the Ontology

### ISSUE THREAD

**Issue by xrotwang** [cldf/cldf#52]
rather than the under-specified `slice` property.

See also #49

**Comment by cysouw** [comment]
Can you explain with a simple example how this would work? Suppose I have a string with a secondary separator somewhere in the data, e.g. "asdf+asdf", where "+" is the secondary separator. How do I refer to the second part of this string?

```
<formTable: table1.tsv>
ID   FORM         MEANING   LANGUOID
23  asdf+asdf   tree             somelanguage

<otherTable linking to formTable>
ID   FORM_ID          .....   ???
67  table1.tsv: 23   ......   ???
```

**Comment by xrotwang** [comment]
Using slices you mean?
```python
>>> ['asdf', 'asdf'][1:]
['asdf']
```

**Comment by xrotwang** [comment]
The semantics of the `segmentSlice` property would be: 
> A slice, specifying a sub-set of segments in the `Segment` column of the row in `FormTable` with primary key `Form_ID`

**Comment by cysouw** [comment]
Ok, I get it.

However, in the proposal for an `alignmentAnnotationTable` (issue #51) the slice refers to an `Annotation` in a `cognateTable`. And there might be other uses of slices. Can we specify that somewhere?

**Comment by xrotwang** [comment]
Yes, the place to specify this would be the ontology. We went the same way with reference properties, of which we now have quite a few in ontology. It seems a bit repetitive, but I think there's no way around being explicit: Whenever you have a column using slices to refer to something and this case is useful for analysis software this requires a new property in the Ontology.
