### ISSUE TITLE
Minor issues in the ontology

### ISSUE THREAD

**Issue by cysouw** [cldf/cldf#54]
I'm going through the [`ontology`](term.rdf), a few comments, please advice:

- the name `Concepticon_ID` for a `Concept Set`: I think we should only use the `_ID` for Reference properties. So maybe this property should be of `dc:type='reference-property'`?
- both `Sound Sequence` and `Subsequence` have the name `Segments`. Is that intentional?
- the description of `Source` is the only one that describes the secondary separator in the text.
- the name `glottocode` is the only one without capitalisation :-).

---

Overall, there are three names attached to each property: the `rdfs:label`, the `csvw:name` and the identifier in the `rdf:about`. In very many cases these three are identical (except for regular camelCase/noSpace/Underscore replacements). However, there are exceptions and I find that confusing. Some are clearly problematic, but others seem to be unnecessary shortcuts.

- Problematic: `ISO 639-3 code`: this label is rendered as `iso639P3Code`, apparently following lexvo.org. The csvw:name is `Iso`, which I find strange. I would propose:
  * rdfs:label `ISO 639 part 3 code`
  * rdf: about `iso639P3Code`
  * csvw:name `ISO_639_Part_3_Code`

- Probably difficult, because already in use are these mismatches:
  * rdfs:label `Lexical Unit`, but csvw:name `Form`. I think the label is too restrictive, and a label `Form` would be much more suitable. 
  * rdfs:label `Sound Sequence`, but csvw:name `Segments`. I would urge to decide for one or the other. There is no reason to confuse people even more ;-).

- Unnecessary:
  * rdfs:label `Primary Text`: why not consquently csvw:name `Primary_Text`
  * rdfs:label `Analyzed Word`: why not consquently csvw:name `Analyzed_Word`
  * rdfs:label `Translated Text`: why not consquently csvw:name `Analyzed_Text`
  * rdfs:label `Motivation Structure`: why not consquently csvw:name `Motivation_Structure`
  * rdfs:label `Prosodic Structure`: why not consquently csvw:name `Prosodic_Structure`

- there is an almost regular replacement of `Reference` into `_ID` for the `csvw:name`, but why not
  * `Meta-language Reference -> Meta_Language_ID` (currently: `Language_ID_Meta`)
  *  `Source Form Reference -> Source_Form_ID` (currently: `Form_ID_Source`)
  * `Target Form Reference -> Target_Form_ID` (currently: `Form_ID_Target`)

- Finally: the link between label `Concept Set` and csvw:name `Concepticon_ID` is confusing. Can we come up with something better here?

**Comment by xrotwang** [comment]
#57 addresses all cases listed above as *unnecessary*.

**Comment by LinguList** [comment]
* LexicalUnit: I think this originally stems from GOLD, but somehow, it seems to be LexicalItem (I am not sure, but I think originally I tried to link as many things as possible to GOLD): http://linguistics-ontology.org/gold/2010/LexicalItem. I'd prefer Form in general, as the LexicalItem is often also what we would label as the "Form_in_Source"
* Sound_Sequence is probably the more telling term, right, although we have been using Segments for a long time now, and there's also the segments-package, etc., which is why I am open-minded, but I'd prefer to change as few things which we use when creating cldf as possible, as it'll force us to do a lot of work on lexibank and also on lingpy and other packages

**Comment by cysouw** [comment]
as a general note: I'd propose to change things as quickly as possible, as the amount of work is now still manageable. If we wait for another year or two it might indeed be impossible to change things anymore :-).

**Comment by cysouw** [comment]
Please close this issue, I have transferred all questions to other issues
