### ISSUE TITLE
Drop rdfs:label property in Ontology

### ISSUE THREAD

**Issue by xrotwang** [cldf/cldf#57]
Since we already have two more name-like attributes for each property, `csvw:name` and the local name in the CLDF namespace, an additional `rdfs:label` seems superfluous, considering that the other names are fairly human readable as well.

Addresses #54

**Comment by cysouw** [comment]
Fine with me. In some cases it might be helpful to write these labels in full in the comment/description, otherwise fine with me. 

However, note that this still does not solve most of the 'inconsistencies' noted in issue #54.

**Comment by xrotwang** [comment]
I realize this. #54 is just a bit too big to be addressed in one go. I'm in the process of breaking it down into independent issues.
