### ISSUE TITLE
Problematic naming issues in ontology

### ISSUE THREAD

**Issue by cysouw** [cldf/cldf#63]
These issues might be more involved, but if we do not change it now, then it will probably never be possible again!

- url `#iso639P3Code` is apparently named this way following lexvo.org. The csvw:name is `Iso`, which I find strange. I would propose csvw:name `ISO_639_Part_3_Code` or `ISO639P3code`
- url `#lexicalUnit`, but csvw:name `Form`. I think the name of the propertyURL is too restrictive as we do not only use this for lexical units. Consider changing the propertyURL to `#form`
- url `#soundSequence`, but csvw:name `Segments`. I would urge to decide for one or the other. There is no reason to confuse people even more ;-).
- the combination propertyURL `#conceptSet` and csvw:name `Concepticon_ID` is confusing. Can we come up with something better here?

(extracted from #54)

**Comment by LinguList** [comment]
* lexicalunit -> Form, I agree with this
* sound sequence should become "Segments"
* concept set can be replaced by Concepticon_ID, as this is the normal ID we use in concepticon

**Comment by cysouw** [comment]
Concerning `Concept Set`: the propertyURL should then be `#concepticonReference` and the csvw:name `Concepticon_ID`. Please note that the the dc:type should then be `dc:type="reference-property"`
