### ISSUE TITLE
Standardize documentation of tables in README.MD files

### ISSUE THREAD

**Issue by SimonGreenhill** [cldf/cldf#75]
I've found these really useful as simple points of entry that will help people understand the various datatypes in CLDF. 

We should have a standardised format (somewhat like an API) to document them. Perhaps also a brief example of a data row?

For example:

```
# SomethingTable

SomethingTable stores <WHAT>

Blah blah free form Description blah blah.

# Fields:

* ID <id> - <stores ID,
* Field1 <type> - stores X 
* Field2 <type> - stores [OtherThing](link to other thing)

# Example

...

```

**Comment by xrotwang** [comment]
Yes, sounds like a really good idea. We could also add a link to a dataset which exhibits the explained data model, e.g. link to the WOLD CLDF as example for a borrowings table. OTOH adding a lot of links makes us susceptible to broken links - but I think that's just the way of the web and we should embrace it :)

**Comment by xrotwang** [comment]
@SimonGreenhill I now create the READMEs by concatenating a "freeform" `description.md` with markdown created from the metadata in JSON, e.g. https://github.com/cldf/cldf/tree/version1.1/components/forms#formtable-formscsv

**Comment by SimonGreenhill** [comment]
cool, thanks!
