### ISSUE TITLE
Comment on the Examples component

### ISSUE THREAD

**Issue by sylvainloiseau** [cldf/cldf#80]
quoting the Example component :

> It should be noted, though, that conversion of CSV examples to and from a format that can be read and edited by Toolbox is very simple. We basically have to map the columns in the CSV specification to Toolbox markers.

It is true, but the correspondance between words and morphems on one hand, and between morphems and glosses on the other, will probably be lost. If I understand it correctly, in the toolbox format, fields are not aligned through the presence of one white space, but through the vertical alignement of the beginning of the items (inserting the correct number of whitespace). It is not that easy to parse this data.

I'm wondering whether the segmentation into "words" could not be expressed through a delimiter (using http://w3c.github.io/csvw/metadata/#cell-separator) -- maybe a single white space -- so that its "parsability" would be preserved.

For instance in the following excerpt the toponyme "Ok Isai" include a white space. The alignment is based on the position of the beginning of the unit:

```
\tx he       to  isai-ma         umwe        uno       ?
\mb he       to  isai       -ma  u      -mwe u    -no  *?
\ge 2S.FEM   man Ok Isaï    -LOC stay   -M.S mary -Ask ***
\ps pr       n   n_toponyme -sfx V      -sfx v    -sfx ***
```

It is also said that:

> Note that words in gloss and aligned text may be further split into morphemes and clitics using - and = as separators according to the Leipzig Glossing Rules. Thus, - and = must not be used for the separator property of the corresponding column.

However, if there is no alignement between "words" in the different fields/tiers/columns, the tokenization with "-" and "=" cannot be used for matching set of text/gloss/category... between fields.

**Comment by xrotwang** [comment]
@sylvainloiseau thanks for the comment! The segmentation into "words" in the CLDF examples component is indeed specified using [a separator property](https://github.com/cldf/cldf/blob/c5f3fce2c496e85b49a8c265618717ef33f75910/components/examples/ExampleTable-metadata.json#L32) - by default a single tab.

But I agree that the way alignment is formatted in toolbox files is sub-optimal, both regarding parsing **and** formatting, so saying conversion to toolbox is "simple" may be somewhat misleading. To be honest, I don't know exactly, toolbox counts the length of a word - in Unicode code points? Or in bytes of a particular encoding, e.g. UTF-8? And if in code points, then with or without [normalization](http://unicode.org/reports/tr15/)?

**Comment by xrotwang** [comment]
Regarding your comment on comparability between tokenized words: Yes, you are right. But making sure tiers are properly aligned is one of the things that can be done automatically, once the format is specified well enough. E.g. for examples in CLDF the `pycldf` package will check whether analyzed text and the gloss line in IGT have the same number of words (see [here](https://github.com/cldf/pycldf/blob/b98f70edba370b0b8aec8f1b56531b2826c4aedf/src/pycldf/validators.py#L18-L25)).

That's the main idea of CLDF: Providing detailed enough specification to make (automated) quality assessment/control possible.
