### ISSUE TITLE
cldf/examples/wordlist/README.md mentions example.tsv* but this is not in the repository

### ISSUE THREAD

**Issue by chrzyki** [cldf/cldf#85]
The `example.tsv*` (i.e. the list itself and its metadata) file is mentioned in the wordlist README but the files are not in the repository.

**Comment by chrzyki** [comment]
I guess this was deprecated by the updated metadata file. If so, we should update the script and README.

**Comment by chrzyki** [comment]
Pinging @LinguList. Should I change the example/README/add files or do you want to do that?

**Comment by chrzyki** [comment]
@LinguList could you have a look at this? Might be neat to have this fixed before the CLDF resubmission. Thanks!

**Comment by LinguList** [comment]
Oh, sorry, did'nt pay attention: if you could change this, this would be helpful, as we have a guest here this week and introduce him to our workflow...

**Comment by chrzyki** [comment]
Sure, no problem. Will do. :)
