### ISSUE TITLE
Corpus-like datastructures for cldf

### ISSUE THREAD

**Issue by LinguList** [cldf/cldf#90]
Working with inter-linear-glossed texts, I came up with a first proposal of how to render a given dataset (could be multi- or mono-lingual) in cldf. My suggestion (having cldf-bench in mind), is shown by the following folder structure:

* `raw/`
  - original glosses
* `etc/`
  - `languages.csv` (may contain only one language with glottocode)
  - `concepts.csv` (contains the concordance of the glosses, including grammatical markers, with an extra-column for concepts that provides some fictive `Grammaticon_ID` and a `Concepticon_ID` and a flag `Type` that is either `lexicon` or `grammar`
  - `orthography.tsv` (as usual)
* `cldf/`
  - `glosses.csv` (lists the text in tsv form, with `ID`, `Text_ID`, `Sentence_ID`, `Phrase_ID`, `Word_ID`, `Phrase`, `Glosses`, with phrase and glosses not necessarily being normalized (this is done in the other files)
  - `forms.csv` (lists in separate form the meaningful and the grammatical items in the text, linking to `Parameter_ID` and `Language_ID` and `Occurrences`, which links to `glosses.csv`, via `Gloss_ID`, and a `Slice`, that is nested, i.e., pointing to the "word" in the gloss, and the position, currently, a space-separted list with secondary segmentation of a colon, i.e., `1:2:1` pointing to `Gloss_ID` 1, `Slice` `[2][1]`)
  - `inventories.csv` (listing all sounds in the data, linking to CLTS, possibly with type-token frequencies)
  - `parameters.csv` (identical with `etc/concepts.csv`)
  - `languages.csv` (identical with `etc/languages.csv`)

Does this make sense, more or less? I think, `inventories.csv` would be useful for cldf, as it will have many usecases, we could even extract it from lexibank-samples, and with `concepts.csv`, we could extract wordlists from inter-linear-glossed text (where linked to concepticon, of course, only).

**Comment by LinguList** [comment]
So two new files are introduced: `inventories.csv` and `glosses.csv`, with `inventories.csv` being useful to further specify a sub-class of cldf-datasets, namely phoible-like data.

**Comment by LinguList** [comment]
I have one working example almost ready, where I could implement this, but with missing specs for cldf, I can't, of course, present this directly in cldf. Or can I create custom tables via `pycldf`?

**Comment by LinguList** [comment]
Maybe it is best if I start by adding a preliminary repository to cldf-datasets, where I share the files,

**Comment by LinguList** [comment]
Ah, one more thing: the crucial question is if we merge parameters or not, I guess. In some sense, it should be easy, if we add a `Parameter_type`, but we separate `Concepticon_ID` already in lexibank, so it would be an empty slot, if the parameter is grammatical (like `Genitive-suffix` or whatever).

**Comment by xrotwang** [comment]
I think we have to be careful with slice notation, since this always requires well defined segmentation. What would be the separator for phrases?

**Comment by LinguList** [comment]
Space. As is common in ilgt. I mean: words are separated by space and dashes separate morphemes inside words and glosses.

**Comment by LinguList** [comment]
But we can adjust this of course. Yet pnly forms.csv would show segmented words.

**Comment by xrotwang** [comment]
I think having parameters of different kinds in the same `parameters.csv` isn't too much of a problem, as long as they are "measured" for the same things - and that seems to be the case here, right? A "word" or "morpheme" can be linked to Concepticon and to "Grammaticon".

**Comment by xrotwang** [comment]
This kind of dataset would be interesting to investigate how semantics and grammar relate to each other, after all, right? So it seems separating these concerns into - say - two different CLDF datasets, which may share some identifiers implicitly, would be a dis-service?

**Comment by LinguList** [comment]
Yes. It is in fact very interesting for linguists. And we gain free wordlists and examples for grammaticon from it.

**Comment by LinguList** [comment]
I just wonder how easy it is to extract only word forms from it for lexibank purposes. I think of loading, e.g. from lingpy, where we expect conception ids. So we probably should have an ID for conception and grammaticon in that file for paramus.

**Comment by LinguList** [comment]
The process of retro-standardization with these data is generally more demanding, but I think it can be basically done:

1. assume a more or less common base format for ilgt and provide some parsers, e.g., from toolbox to this format
2. check for consistency and correct errors
3. extract a concordance, i.e., separate all morphemes in a file, and use this to make an orthoprofile
4. extract a conceptlist, which ignores grammatical markers, to make a link to concepticon
5. extract a markerlist, of grammatical markers, and link them to the non-existing grammaticon or leipzig glossing rules
6. extract a wordlist, where grammatical markers could/should be ignored, and (this is difficult) have a linguist annotate what word forms belong to the same paradigm (i.e.: internal cognates, if a the genitive is completely different from the nominative, or similar things)
7. retro-standardize all by making a cldf-dataset in which a wordlist is added to the original glossed text (checked for errors), plus a list of inventory items, and a list of grammatical items (right now, we assume to have both basic words and markers in `forms.csv`, which makes sense)

It would allow for a more fine-grained integration of actual texts with wordlists, plus all the standardization efforts we are working on, but it would not be as intrusive to demand that all of the ilgt is actually in clts, etc., but rather extract the things by frequency, and retro-standardize them (where possible). Thus, instead of demanding scholars to adhere to clts, when making their ilgt (e.g., also doreka), we'd add functionality to extract what is useful for lexical comparison (and grammatical comparison maybe as well). It's also a way to circumvent the problem that people say: "yes, it's nice, but that's not what I am interested in". They don't need to be interested in, as long as ilgt is standardized enough to allow for retro-standardization (which is also the core of what we do in lexibank by now).

**Comment by LinguList** [comment]
I guess, I'll try to prepare a minimal example which I am doing anyway, with a little library in python for extracting things, and see to which degree I can by myself look into cldf/pycldf to make a proposal. In the worst case, I'll produce a bunch of tsv-files that show my idea without proposing new datatypes for cldf.

**Comment by tresoldi** [comment]
It is not interlinear text, as the analogy holds stronger with cognates, but I can see adapting this to my data on the Divine Comedy: https://raw.githubusercontent.com/tresoldi/criticaldante/master/data/tresoldi.nex

Question: how much overlap would this have with the TEI? [https://en.wikipedia.org/wiki/Text_Encoding_Initiative] I would really prefer something cldf-like, TEI can be as difficult to properly use as any serious XML format (which is why I was lazy with the Dante project and just coded everything in a big, dumb CSV)

**Comment by LinguList** [comment]
I tend to ignore TEI. I'll only mention it when being forced by reviewers. As to the divine comedy data: isn't that parallel text, in some sense? For parallel text, we have a module. I'd argue: ilgt is different, as you have a phrase and a gloss for the phrase.

**Comment by tresoldi** [comment]
In a way it is both parallel text and interlinear, even though I am rendering it as parallel in NEXUS.

There are 10 manuscripts, some with no corrections, others with different layers of interlinear correction by different hands at different times (usually cancelling some word and writing the "correct" one). `Ash_orig` is the original writing, `Ash` is the manuscript with the original copyist corrections (i.e., as he wanted his final product to be read), `Ash_c1` the text as read with the corrections from a second, different person, `Ash_c2` the text with the corrections of a third person (which corrects both the copyst and the first corrector, sometimes reverting the decision of the latter to the choice of the original).

However, physically, the manuscript is a single document.

**Comment by tresoldi** [comment]
I suppose I follow the most etymological definition, something which is between lines, which is the case for my data. Apart a handful of cases (such as glosses with synonyms, but I am really talking about four or five instances), it is not as in Biblical glosses, however -- if this is the main goal of the new data structure, indeed my data does not fit it.

My question is how to represent parallel interlinear documents, with this loose definition of interlinear. Just abstracting them as parallel texts might not be enough due to the interdependency of the data within a document, both in world-3 (as in any case of constrained writing, even more with the metric of this work) but also in the interaction of worlds 1 and 3.

**Comment by LinguList** [comment]
So it's a different definition than the interlinear in interlinear glossed text, right? As ILGT is quite specific, in my opinion, also with respect to use cases.

**Comment by tresoldi** [comment]
Yes, even the technical term in stemmatics is different: they are not "glosses", but "lessons". I suppose we drop the stemmatics issue, then, sorry for hijacking the topic.

**Comment by LinguList** [comment]
No, it is completely fine, I also want to work on cldf for rhyme annotations. I think it's just important to distinguish where the problems are, and you could open another issue for this specific problem.

**Comment by xrotwang** [comment]
See TextCorpus module.
