### ISSUE TITLE
Reference properties for more catalogs

### ISSUE THREAD

**Issue by xrotwang** [cldf/cldf#92]
The ontology should include properties to exlicitly reference
- CLTS
- GBIF

**Comment by tresoldi** [comment]
+1, especially for CLTS

**Comment by xrotwang** [comment]
@tresoldi @LinguList what should we use as sound ID in CLTS? The sound name, i.e. [voiceless_dental_click_consonant](https://clts.clld.org/parameters/voiceless_dental_click_consonant) ?

**Comment by xrotwang** [comment]
GBIF references should be integer TaxonIDs from the [GBIF Backbone Taxonomy](https://www.gbif.org/dataset/d7dddbf4-2cf0-4f39-9b2a-bb099caae36c#description)

**Comment by xrotwang** [comment]
GBIF
```xml
    <rdf:Property rdf:about="http://cldf.clld.org/v1.0/terms.rdf#gbifReference"
                  dc:type="reference-property">
        <rdfs:comment>
              References a taxonomic unit in GBIF's Backbone Taxonomy.
        </rdfs:comment>
        <csvw:name>"GBIF_ID"</csvw:name>
        <csvw:datatype>{"base": "string", "format": "[0-9]+"}</csvw:datatype>
        <csvw:valueUrl>"https://www.gbif.org/species/{GBIF_ID}"</csvw:valueUrl>
        <rdfs:range rdf:resource="http://www.w3.org/2000/01/rdf-schema#Literal"/>
        <rdfs:seeAlso rdf:resource="https://www.gbif.org/dataset/d7dddbf4-2cf0-4f39-9b2a-bb099caae36c#description" />
    </rdf:Property>
```

**Comment by xrotwang** [comment]
CLTS
```xml
    <rdf:Property rdf:about="http://cldf.clld.org/v1.0/terms.rdf#cltsReference"
                  dc:type="reference-property">
        <rdfs:comment>
              References a sound in the Cross-Linguistic Transcription Systems database
        </rdfs:comment>
        <csvw:name>"CLTS_ID"</csvw:name>
        <csvw:datatype>{"base": "string", "format": "[a-z_-]+"}</csvw:datatype>
        <csvw:valueUrl>"https://clts.clld.org/parameters/{CLTS_ID}"</csvw:valueUrl>
        <rdfs:range rdf:resource="http://www.w3.org/2000/01/rdf-schema#Literal"/>
        <rdfs:seeAlso rdf:resource="https://clts.clld.org" />
    </rdf:Property>
```

**Comment by xrotwang** [comment]
@LinguList what would be the name of the NULL phoneme - when Ø is the grapheme?

**Comment by LinguList** [comment]
Since it is a marker, it does not have a real name so far.

**Comment by LinguList** [comment]
No, I was wrong, the name is the grapheme, so the name is `Ø`. 

https://github.com/cldf-clts/pyclts/blob/f725bbf0073fc9e3fcb46ef55e40ba60118e33ba/src/pyclts/models.py#L224-L240

If we want to change this, we'd have to do make a new small release of pyclts. Adding the marker, as planned, would only require us to release the new CLTS data (small release).

**Comment by xrotwang** [comment]
ok, grapheme kann man wohl nehmen.

**Comment by xrotwang** [comment]
```python
>>> URITemplate('http://example.org/{i}').expand(i='Ø')
'http://example.org/%C3%98'
```

**Comment by xrotwang** [comment]
So the "inlinkable" sound should now be linked to [NA](https://clts.clld.org/parameters/NA)
