### ISSUE TITLE
Specify format for adding phylogenetic data to CLDF

### ISSUE THREAD

**Issue by xrotwang** [cldf/cldf#96]
We should find a way to make phylogenetic data (a.k.a. trees) part of CLDF. With such a specification, we could generically support tools like
https://camayal.info/wa/treetom/

**Comment by xrotwang** [comment]
While Nexus might look like a candidate here, I'd be reluctant to even base a spec on it - because it would defeat the whole purpose of CLDF as **well-defined**, simple format.

So I guess, a phylogenetic component for CLDF woul rather look like a constrained version of Newick, including spec for
- file encoding
- label formatting

and considering that we don't support Nexus directly, a couple of tools or recipes to turn common Nexus variants into such a component.

**Comment by xrotwang** [comment]
@SimonGreenhill @LinguList @chrzyki Another question is what semantics we should attach to a `Trees` component - or whether we can do that at all. E.g. can we consider a single tree to be a consensus tree from a bayesian analysis? But what about trees derived from distance matrices, then?

So maybe the question should be asked the other way round: Would a tree component without any semantics make sense - i.e. just having a way to throw a bunch of trees into a CLDF dataset?

**Comment by xrotwang** [comment]
If a tree component wouldn't have any semantics, would we need to allow for multiple such components, e.g. to add posterior tree sets **and** consensus tree?

**Comment by SimonGreenhill** [comment]
Yes, I'm a little reluctant to create a new standard for trees after nexus, but can see the usefulness. 

An easy way to handle this is as a csv file that has a column containing the tree in newick format (i.e. `((a,b),c)`), with one row per tree. The various bits of metadata we'd need or want are:

1. `Name`: Nexus specifies a name for each tree `tree name = ((a,b),c);`. This is often not used (so `tree = ((a,b),c);` is valid), but this can be useful e.g. bayesian programs often use it to store the MCMC sample generation.

2. `Units`: The branch length units e.g. none, time, years, millennia, changes, substitutions, etc. Would be good to have a validator on this to constrain the number of things that can be entered.

3. `Method`: how the trees were built? (maybe not useful, and could be replaced by tree name?)

4. `Type` (e.g "posterior", "consensus")

5. `Rooting` - nexus can specify if a tree is rooted or unrooted: `tree name = [&R] ((a,b),c);` or `tree name = [&U] ((a,b),c);`. This would get lost if we're only storing the newick information and treename, so roundtripping wouldn't work unless we extracted rooted/unrooted/none.


Converting to/from common tree formats should be pretty easy -- to newick, it's just export the tree column, to nexus it's:

```
#nexus;
begin trees;
tree <name> = [&<rooting>] <newick>;
;
end;
```

Another thing worth thinking about is whether we want to extract taxa labels into their own file (e.g. `taxa.csv` in DPLACE) as otherwise we don't know what's in the trees unless we parse the newick representation.

It might be nice to "compress" the tree format (i.e. remove labels from tree and replace with numbers), so `((a,b),c);` becomes `((1,2),3);`. This means that the trees take up (much) less space and is handled by nexus easily: https://github.com/D-PLACE/dplace-data/blob/master/phylogenies/birchall_et_al2016/summary.trees. Having a taxa.csv would make this pretty transparent as taxa.csv just becomes the `translate` block. 

Have a look at the things I've been collecting in [phlorest](https://github.com/SimonGreenhill/phlorest) for examples (this is private for the moment).

**Comment by RustyGray** [comment]
Yes! R.

Russell Gray
Director Max Planck Institute for the Science of Human History
Kahlaische Strasse 10
D-07745 Jena, GERMANY
TEL: +49-3641-68 68 01
FAX: +49-3641-68 68 68
Departmental Administrator  schueck@shh.mpg.de<mailto:schueck@shh.mpg.de>
http://www.shh.mpg.de/2375/en
http://scholar.google.co.nz/citations?user=FzE-34YAAAAJ&hl=en
Database of places, language, culture & environment: www.d-place.org

On 17. Feb 2020, at 19:53, Robert Forkel <notifications@github.com<mailto:notifications@github.com>> wrote:


We should find a way to make phylogenetic data (a.k.a. trees) part of CLDF. With such a specification, we could generically support tools like
https://camayal.info/wa/treetom/

**Comment by xrotwang** [comment]
@SimonGreenhill Regarding "compression" and tree labels: I'd say in the CLDF context labels in the Newick **must** be `LanguageTable` `ID`s only (well maybe with the exception of some comment format). Stuff like tree-specific original labels would then need to be added to `LanguageTable`, but I wouldn't further specify this.

Regarding `Method` and `Type`: I'd make these informal, optional metadata - unless we'd have hopes to further constrain them. Maybe easier to specify - for dataset creators - and equally informative (if not more so) would be the tool used to create the tree. I'm thinking of BEAST's annotation format - if we now it's a BEAST tree, we'd know what to look for.

**Comment by SimonGreenhill** [comment]
Yes to the above. One thing though, do we want to have one trees file or multiple? if it's one file then we need to be able to distinguish from a consensus/summary tree and the posterior (= `Type` or `Method`). If it's multiple files then we could could have one tree file for the summary tree, and one for the posterior.

**Comment by xrotwang** [comment]
I'd say just one tree table - and specification of type or method is left to the dataset creator, but unspecified (?). This would mirror the way we'd deal with different types in `ParameterTable` at the moment. Or do you think we could come up with a fairly complete controlled vocabulary for `Type` or `Method`?

I think I'd go by the CLDF principle here again: Only things that have automated computational applications should be part of the CLDF spec. But maybe `pypipeline` is already enough to roll the `posterior` / `consensus` distinction into CLDF?

**Comment by SimonGreenhill** [comment]
Hmm, I'm thinking of the types of analyses I'd want to do. These are things like (1) take out the summary tree and look at it, (2) take out all the trees in the posterior (BUT not the summary tree) and calculate some statistics on them. 

Therefore being able to do that easily would be good, which means I think a non-optional restricted vocab column would be useful (although coming up with a good vocab might be hard), along with an optional one.

One issue is that there's not one type of 'summary' tree -- there's lots of methods. So it's not inconceivable that a dataset could have more than one summary.

Another issue is that the "posterior" is just one type of analysis, there are lots of older methods that give multiple trees e.g. [this](https://github.com/SimonGreenhill/phlorest/blob/master/gray_and_jordan2000/original/post-nature.trees) has a set of "equally most parsimonious trees". 

So I think what this means is that the we should have a non-optional field `Type`, with vocab `{"summary", "sample"}` where:
- a paper that's used a method like parsimony to find a single tree only has "summary"  (e.g. [Chacon and List](https://github.com/D-PLACE/dplace-data/tree/master/phylogenies/chacon_and_list2015)
- while the study I linked above has a "summary" and a set of "sample"'s
- a Bayesian analysis like [Birchall et al](https://github.com/D-PLACE/dplace-data/tree/master/phylogenies/birchall_et_al2016) has a "summary" and lots of "sample"s.

If the creator wants, they can further specify more details in the optional `Method` field?

**Comment by SimonGreenhill** [comment]
i.e. "summary" is defined as an overall summary tree (of whatever method, which can be specified in more detail in a `Method`, while "sample" is a tree sampled from the analysis under which ever method, but is not an overall summary of the analysis.


(or is `Description` a better name rather than `Method`?)

**Comment by LinguList** [comment]
Or TREX: http://dighl.github.io/TREX/

**Comment by xrotwang** [comment]
@SimonGreenhill yes, we also have `Name` and `Description` available, but I'd guess that `Description` would be more comprehensive and more human readable. So here's the kind of logic I can see derived from `Type` and `Method`:

- `Type == 'summary'`: This tree can be used in isolation, e.g. to plot data against it. `Method` can be used to disambiguate multiple summary trees in the same dataset, but so can `Name` or `Description`.
- `Type == 'sample'`: Trees must be grouped (by `Method`) to form a tree set that can be analyzed with methods that handle tree sets.

**Comment by SimonGreenhill** [comment]
Sounds good. 

I suggested `Name` above to store the information in `name` in this `tree <name> = [&<rooting>] <newick>;`, but given that `name` here should be relatively slug-like, then this makes sense to use these as `ID`

**Comment by xrotwang** [comment]
@SimonGreenhill I think using the `Name` column for whatever Nexus has a `<name>` makes sense. Possibly the tool converting CLDF trees to Nexus might need to massage a `Name` - if it didn't come from Nexus originally.

**Comment by SimonGreenhill** [comment]
Ok, sounds good. I guess the next step is to throw some real data into it (DPLACE phylogenies?) and see if there's anything missing or uncomfortable?

**Comment by xrotwang** [comment]
Yes, we could actually do that - turn D-PLACE into an "artificial" CLDF dataset, with one parameter: "Society mapping", and a bunch of trees.

**Comment by xrotwang** [comment]
So example will go here https://github.com/cldf-datasets/dplace

**Comment by xrotwang** [comment]
renamed to dplacetrees: https://github.com/cldf-datasets/dplacetrees

**Comment by xrotwang** [comment]
@SimonGreenhill @LinguList @chrzyki so is this what we want: https://github.com/cldf-datasets/dplacetrees/tree/master/cldf
It's sort of reasonable in terms of size - and D-PLACE is presumably the "worst" case when it comes to number and size of trees.

**Comment by SimonGreenhill** [comment]
Looks good -- the trees from DPLACE come to 50mb, so trees.csv doesn't massively inflate that (55mb). The treelabels.csv is a bit annoyingly large, but I guess we need it?

**Comment by xrotwang** [comment]
Switching to integer tree IDs, `treelabels.csv` clocks in at 7MB.

**Comment by SimonGreenhill** [comment]
That's much nicer -- and surely we don't loose much with that, right?

**Comment by xrotwang** [comment]
No, I'd add the D-PLACE phylogeny ID in a separate column of `trees.csv`.

**Comment by SimonGreenhill** [comment]
perfect.

**Comment by chrzyki** [comment]
Very nice! Anything I can do to help testing this?

**Comment by xrotwang** [comment]
Possibly the next step would be basing the pypipeline code on this.

**Comment by xrotwang** [comment]
So, coming back to this for the refactoring of D-PLACE.

**Comment by xrotwang** [comment]
For `atkinson2006`, it looks as follows ATM:
```
$ cldfbench makecldf cldfbench_atkinson2006.py 
INFO    running _cmd_makecldf on atkinson2006 ...
WARNING Summary tree references undefined inner node Huastecan
WARNING Summary tree references undefined inner node MayaProper
WARNING Summary tree references undefined inner node Kanjobalan
WARNING Summary tree references undefined inner node EasternMayan
WARNING Summary tree references undefined inner node Quichean
WARNING Summary tree references undefined inner node SipaSaca
WARNING Summary tree references undefined inner node CakTzut
WARNING Summary tree references undefined inner node Poco
WARNING Summary tree references undefined inner node Mamean
WARNING Summary tree references undefined inner node CholTzetYuc
WARNING Summary tree references undefined inner node CholYuc
WARNING Summary tree references undefined inner node Cholan
WARNING Summary tree references undefined inner node Yucatecan
WARNING Summary tree references undefined inner node Tzeltalan
INFO    ... done atkinson2006 [9.7 secs]
```

**Comment by xrotwang** [comment]
I'm not against having nexus files in the cldf dir - in addition to the
trees.csv. But trees.csv just makes describing the metadata and validating
it a lot easier, e.g. linking the tree to a source. So basically, trees.csv
will act as table of contents for the nexus files, even if it actually
duplicates the content.

Simon J Greenhill ***@***.***> schrieb am Do., 14. Okt. 2021,
03:21:

**Comment by xrotwang** [comment]
Regarding internal nodes: With the cldfbench setup, when nexus files in `cldf/` are not just copied from `raw/`, but re-written, we could keeping (and mapping) of internal nodes an editorial decision of whoever maintains the phylogeny.

**Comment by SimonGreenhill** [comment]
Great, sounds good. Keen to keep the beast annotations if we can. 

In my experience, .trees or .tre or .tree seems to be common for nexus-that-contain-trees, while .nex is used for data or data+trees. However, it doesn't matter, of course, but most tree viewing apps seem to default to looking for .tre or .trees. 

Personally, I prefer .trees as it's transparent what the file contains and it's the beast default (and about 90% of the things in phlorest are from beast). Distinguishing .tree/.trees seems like overkill, and .tre seems like a painful DOS hangover

**Comment by LinguList** [comment]
I could provide one on Chinese dialects later this week.

**Comment by LinguList** [comment]
I'd opt for a generic way and to derive the specific distance matrix as a requirement from it.

**Comment by SimonGreenhill** [comment]
you can get matrices with non-zeros on the diagonal (e.g. rate matrices) so it might be nice to handle the more generic case rather than just zeros (and I guess you could also have a similarity matrix so 1's on the diagonal)

**Comment by xrotwang** [comment]
At 57 comments, this thread starts getting a bit unwieldy. But since we already discussed most relevant issues, I think we can start sketching the spec for phylogeny support in CLDF in the wiki https://github.com/cldf/cldf/wiki/Phylogenies-in-CLDF

**Comment by xrotwang** [comment]
I'd welcome feedback on the open issues here: https://github.com/cldf/cldf/wiki/Phylogenies-in-CLDF#issues

**Comment by LinguList** [comment]
For nexus file format, I'd say that leading #nexus is all that is needed. There are so many corruptions to nexus, that this is probably easiest.

**Comment by LinguList** [comment]
Newick essentially roots trees, and I don't know of an unrooted tree format. But since trees are reconstructed from methods that do not root, I'd argue that rooting is an important property, also because many phylogenetic algorithms work differently for rooted vs. unrooted trees, etc.

**Comment by SimonGreenhill** [comment]
I think we'll need to sniff for "#NEXUS\n". 

One thing that might be worth thinking about is if ID/Name/position in tree file (i.e. {1...n}) is ever going to be different. Feels a little redundant to have ID/Name as different columns.

Another field that might be useful is something like 'units' to describe what units the branches are in.

Or `format` -- it might be nice  to specify what format the tree is in e.g. ETE3's [tree formats](http://etetoolkit.org/docs/latest/tutorial/tutorial_trees.html#reading-and-writing-newick-trees). This would be a pain to write code to detect though, so might be too much effort.

**Comment by xrotwang** [comment]
I think the `ID`/`Name` distinction should stay, because
- `ID` is often constrained by all sorts of use cases (e.g. a unquoted node label in Newick - which already precludes using `(),`)
- for use cases like `CLDF markdown`, an explicit human readable label for each object in a CLDF component is desirable.

**Comment by xrotwang** [comment]
I wouldn't bother about specifying newick more narrowly - e.g. following ETE's nomenclature. I'm not really sure, actually, why this is needed in ETE3. Whenever I used ETE3, I'd basically plug in numbers from 1-7 and take the first one that doesn't raise error :)

**Comment by xrotwang** [comment]
@SimonGreenhill  re `unit`: Do you think the set of allowed values we have in phlorest ( https://github.com/phlorest/phlorest/blob/d94528df53a895bc7918f7c5f7ac467fabc5053e/src/phlorest/metadata.py#L9-L16 ) could be used - or are there any obvious additions you'd have?

**Comment by SimonGreenhill** [comment]
yes -- I think these units are the ones I've found necessary to date. 

(and that's also my strategy for ete3 too :)

happy to not add the `format` spec, and keep ID/Name

**Comment by xrotwang** [comment]
@SimonGreenhill "unit" or "scale"?

**Comment by xrotwang** [comment]
I think "unit" is the correct term. "Scale" already implies an agreed upon unti.

**Comment by SimonGreenhill** [comment]
agreed -- I prefer unit.
